// packages/react/src/RpImageEditor.tsx
import React, { useRef, useEffect, useCallback } from 'react';
import { RpImageEditor, RpEditorConfig, RpEditorResult } from '@rageshpikalmunde/rp-image-editor';

export interface RpImageEditorProps {
  /** Image source — File, Blob, or URL string */
  image: File | Blob | string | null;

  /** Editor configuration */
  config?: Partial<RpEditorConfig>;

  /** Called when user clicks Apply */
  onImageEdited?: (result: RpEditorResult) => void;

  /** Called when editor encounters an error */
  onError?: (error: Error) => void;

  /** Custom class name for the container */
  className?: string;

  /** Custom style for the container */
  style?: React.CSSProperties;
}

/**
 * React component that renders the image editor inline.
 * For modal usage, use the `useRpImageEditor()` hook instead.
 */
export const RpImageEditorComponent: React.FC<RpImageEditorProps> = ({
  image,
  config,
  onImageEdited,
  onError,
  className,
  style,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const editorRef = useRef<RpImageEditor | null>(null);

  useEffect(() => {
    if (!image || !containerRef.current) return;

    // Destroy previous editor
    if (editorRef.current) {
      editorRef.current.destroy();
    }

    const editor = new RpImageEditor(containerRef.current, config);
    editorRef.current = editor;

    editor.on('error', (err) => onError?.(err));

    editor.loadImage(image).catch((err) => onError?.(err));

    return () => {
      editor.destroy();
      editorRef.current = null;
    };
  }, [image]); // Re-init when image changes

  return (
    <div
      ref={containerRef}
      className={className || 'rp-image-editor-host'}
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        minHeight: 300,
        ...style,
      }}
    />
  );
};

// packages/angular/src/lib/rp-image-editor.component.ts
import { Component, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild, AfterViewInit } from '@angular/core';
import { RpImageEditor, RpEditorConfig, RpEditorResult } from '@rageshpikalmunde/rp-image-editor';

@Component({
  selector: 'rp-image-editor',
  template: `<div #editorContainer class="rp-image-editor-host" [style.width]="'100%'" [style.height]="'100%'" [style.display]="'flex'" [style.flexDirection]="'column'"></div>`,
  styles: [`:host { display: block; width: 100%; height: 100%; } .rp-image-editor-host { min-height: 300px; }`]
})
export class RpImageEditorComponent implements AfterViewInit, OnDestroy {
  @ViewChild('editorContainer', { static: true }) containerRef!: ElementRef<HTMLElement>;

  /** Image source — File, Blob, or URL string */
  @Input() image: File | Blob | string | null = null;

  /** Editor configuration */
  @Input() config: Partial<RpEditorConfig> = {};

  /** Emitted when user clicks Apply — contains the edited image result */
  @Output() imageEdited = new EventEmitter<RpEditorResult>();

  /** Emitted when user clicks Close/Cancel */
  @Output() editorClosed = new EventEmitter<void>();

  /** Emitted when an error occurs */
  @Output() editorError = new EventEmitter<Error>();

  private editor: RpImageEditor | null = null;

  ngAfterViewInit(): void {
    if (this.image) {
      this.initEditor();
    }
  }

  ngOnDestroy(): void {
    this.destroyEditor();
  }

  /**
   * Programmatically load an image (can be called after component init)
   */
  async loadImage(source: File | Blob | string): Promise<void> {
    this.image = source;
    await this.initEditor();
  }

  /**
   * Get the edited result programmatically
   */
  async getResult(): Promise<RpEditorResult | null> {
    try {
      return await this.editor?.getResult() ?? null;
    } catch (err) {
      this.editorError.emit(err as Error);
      return null;
    }
  }

  /**
   * Apply and emit result
   */
  async apply(): Promise<void> {
    const result = await this.getResult();
    if (result) {
      this.imageEdited.emit(result);
    }
  }

  /**
   * Close the editor
   */
  close(): void {
    this.destroyEditor();
    this.editorClosed.emit();
  }

  /**
   * Reset to original image
   */
  async reset(): Promise<void> {
    await this.editor?.reset();
  }

  private async initEditor(): Promise<void> {
    this.destroyEditor();

    if (!this.image || !this.containerRef?.nativeElement) return;

    this.editor = new RpImageEditor(this.containerRef.nativeElement, this.config);

    this.editor.on('error', (err) => {
      this.editorError.emit(err);
    });

    try {
      await this.editor.loadImage(this.image);
    } catch (err) {
      this.editorError.emit(err as Error);
    }
  }

  private destroyEditor(): void {
    if (this.editor) {
      this.editor.destroy();
      this.editor = null;
    }
  }
}
